apiVersion: v2
name: osm-device-adapter-secrets
description: Secrets management chart for OSM Device Adapter
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - osm
  - secrets
  - oauth

maintainers:
  - name: m0rjc

home: https://github.com/m0rjc/OsmDeviceAdapter
sources:
  - https://github.com/m0rjc/OsmDeviceAdapter
